name: Hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master